// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ContainerProbeHTTPScheme string

const (
	ContainerProbeHTTPSchemeHTTP ContainerProbeHTTPScheme = "http"
)

func (e ContainerProbeHTTPScheme) ToPointer() *ContainerProbeHTTPScheme {
	return &e
}

func (e *ContainerProbeHTTPScheme) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		*e = ContainerProbeHTTPScheme(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerProbeHTTPScheme: %v", v)
	}
}
