// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContainerGroupProbeExec struct {
	Command []string `json:"command"`
}

func (o *ContainerGroupProbeExec) GetCommand() []string {
	if o == nil {
		return []string{}
	}
	return o.Command
}
