// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContainerGroupNetworking - Represents container group networking parameters
type ContainerGroupNetworking struct {
	Auth     bool                        `json:"auth"`
	DNS      string                      `json:"dns"`
	Port     int64                       `json:"port"`
	Protocol ContainerNetworkingProtocol `json:"protocol"`
}

func (o *ContainerGroupNetworking) GetAuth() bool {
	if o == nil {
		return false
	}
	return o.Auth
}

func (o *ContainerGroupNetworking) GetDNS() string {
	if o == nil {
		return ""
	}
	return o.DNS
}

func (o *ContainerGroupNetworking) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *ContainerGroupNetworking) GetProtocol() ContainerNetworkingProtocol {
	if o == nil {
		return ContainerNetworkingProtocol("")
	}
	return o.Protocol
}
