// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ContainerRestartPolicy string

const (
	ContainerRestartPolicyAlways    ContainerRestartPolicy = "always"
	ContainerRestartPolicyOnFailure ContainerRestartPolicy = "on_failure"
	ContainerRestartPolicyNever     ContainerRestartPolicy = "never"
)

func (e ContainerRestartPolicy) ToPointer() *ContainerRestartPolicy {
	return &e
}

func (e *ContainerRestartPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "always":
		fallthrough
	case "on_failure":
		fallthrough
	case "never":
		*e = ContainerRestartPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerRestartPolicy: %v", v)
	}
}
