// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContainerGroupProbe - Represents container group probe
type ContainerGroupProbe struct {
	Exec                *ContainerGroupProbeExec `json:"exec,omitempty"`
	FailureThreshold    int64                    `json:"failure_threshold"`
	Grpc                *ContainerGroupProbeGrpc `json:"grpc,omitempty"`
	HTTP                *ContainerGroupProbeHTTP `json:"http,omitempty"`
	InitialDelaySeconds int64                    `json:"initial_delay_seconds"`
	PeriodSeconds       int64                    `json:"period_seconds"`
	SuccessThreshold    int64                    `json:"success_threshold"`
	TCP                 *ContainerGroupProbeTCP  `json:"tcp,omitempty"`
	TimeoutSeconds      int64                    `json:"timeout_seconds"`
}

func (o *ContainerGroupProbe) GetExec() *ContainerGroupProbeExec {
	if o == nil {
		return nil
	}
	return o.Exec
}

func (o *ContainerGroupProbe) GetFailureThreshold() int64 {
	if o == nil {
		return 0
	}
	return o.FailureThreshold
}

func (o *ContainerGroupProbe) GetGrpc() *ContainerGroupProbeGrpc {
	if o == nil {
		return nil
	}
	return o.Grpc
}

func (o *ContainerGroupProbe) GetHTTP() *ContainerGroupProbeHTTP {
	if o == nil {
		return nil
	}
	return o.HTTP
}

func (o *ContainerGroupProbe) GetInitialDelaySeconds() int64 {
	if o == nil {
		return 0
	}
	return o.InitialDelaySeconds
}

func (o *ContainerGroupProbe) GetPeriodSeconds() int64 {
	if o == nil {
		return 0
	}
	return o.PeriodSeconds
}

func (o *ContainerGroupProbe) GetSuccessThreshold() int64 {
	if o == nil {
		return 0
	}
	return o.SuccessThreshold
}

func (o *ContainerGroupProbe) GetTCP() *ContainerGroupProbeTCP {
	if o == nil {
		return nil
	}
	return o.TCP
}

func (o *ContainerGroupProbe) GetTimeoutSeconds() int64 {
	if o == nil {
		return 0
	}
	return o.TimeoutSeconds
}
