// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContainerGroupProbeHTTP struct {
	Headers []HTTPHeaders             `json:"headers,omitempty"`
	Path    string                    `json:"path"`
	Port    int64                     `json:"port"`
	Scheme  *ContainerProbeHTTPScheme `json:"scheme,omitempty"`
}

func (o *ContainerGroupProbeHTTP) GetHeaders() []HTTPHeaders {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ContainerGroupProbeHTTP) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *ContainerGroupProbeHTTP) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *ContainerGroupProbeHTTP) GetScheme() *ContainerProbeHTTPScheme {
	if o == nil {
		return nil
	}
	return o.Scheme
}
