// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ContainerNetworkingProtocol string

const (
	ContainerNetworkingProtocolHTTP ContainerNetworkingProtocol = "http"
)

func (e ContainerNetworkingProtocol) ToPointer() *ContainerNetworkingProtocol {
	return &e
}

func (e *ContainerNetworkingProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		*e = ContainerNetworkingProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerNetworkingProtocol: %v", v)
	}
}
