// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContainerGroupProbeTCP struct {
	Port int64 `json:"port"`
}

func (o *ContainerGroupProbeTCP) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}
