// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContainerGroupList - Represents a list of container groups
type ContainerGroupList struct {
	Items []ContainerGroup `json:"items"`
}

func (o *ContainerGroupList) GetItems() []ContainerGroup {
	if o == nil {
		return []ContainerGroup{}
	}
	return o.Items
}
