// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/utils"
)

type ContainerGroupsQuotas struct {
	ContainerInstanceQuota                  int64  `json:"container_instance_quota"`
	MaxContainerGroupReallocationsPerMinute *int64 `default:"10" json:"max_container_group_reallocations_per_minute"`
	MaxContainerGroupRecreatesPerMinute     *int64 `default:"10" json:"max_container_group_recreates_per_minute"`
	MaxContainerGroupRestartsPerMinute      *int64 `default:"10" json:"max_container_group_restarts_per_minute"`
	MaxCreatedContainerGroups               int64  `json:"max_created_container_groups"`
}

func (c ContainerGroupsQuotas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContainerGroupsQuotas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ContainerGroupsQuotas) GetContainerInstanceQuota() int64 {
	if o == nil {
		return 0
	}
	return o.ContainerInstanceQuota
}

func (o *ContainerGroupsQuotas) GetMaxContainerGroupReallocationsPerMinute() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxContainerGroupReallocationsPerMinute
}

func (o *ContainerGroupsQuotas) GetMaxContainerGroupRecreatesPerMinute() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxContainerGroupRecreatesPerMinute
}

func (o *ContainerGroupsQuotas) GetMaxContainerGroupRestartsPerMinute() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxContainerGroupRestartsPerMinute
}

func (o *ContainerGroupsQuotas) GetMaxCreatedContainerGroups() int64 {
	if o == nil {
		return 0
	}
	return o.MaxCreatedContainerGroups
}
