// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CountryCode string

const (
	CountryCodeAf CountryCode = "af"
	CountryCodeAl CountryCode = "al"
	CountryCodeDz CountryCode = "dz"
	CountryCodeAs CountryCode = "as"
	CountryCodeAd CountryCode = "ad"
	CountryCodeAo CountryCode = "ao"
	CountryCodeAi CountryCode = "ai"
	CountryCodeAq CountryCode = "aq"
	CountryCodeAg CountryCode = "ag"
	CountryCodeAr CountryCode = "ar"
	CountryCodeAm CountryCode = "am"
	CountryCodeAw CountryCode = "aw"
	CountryCodeAu CountryCode = "au"
	CountryCodeAt CountryCode = "at"
	CountryCodeAz CountryCode = "az"
	CountryCodeBs CountryCode = "bs"
	CountryCodeBh CountryCode = "bh"
	CountryCodeBd CountryCode = "bd"
	CountryCodeBb CountryCode = "bb"
	CountryCodeBy CountryCode = "by"
	CountryCodeBe CountryCode = "be"
	CountryCodeBz CountryCode = "bz"
	CountryCodeBj CountryCode = "bj"
	CountryCodeBm CountryCode = "bm"
	CountryCodeBt CountryCode = "bt"
	CountryCodeBo CountryCode = "bo"
	CountryCodeBq CountryCode = "bq"
	CountryCodeBa CountryCode = "ba"
	CountryCodeBw CountryCode = "bw"
	CountryCodeBv CountryCode = "bv"
	CountryCodeBr CountryCode = "br"
	CountryCodeIo CountryCode = "io"
	CountryCodeBn CountryCode = "bn"
	CountryCodeBg CountryCode = "bg"
	CountryCodeBf CountryCode = "bf"
	CountryCodeBi CountryCode = "bi"
	CountryCodeCv CountryCode = "cv"
	CountryCodeKh CountryCode = "kh"
	CountryCodeCm CountryCode = "cm"
	CountryCodeCa CountryCode = "ca"
	CountryCodeKy CountryCode = "ky"
	CountryCodeCf CountryCode = "cf"
	CountryCodeTd CountryCode = "td"
	CountryCodeCl CountryCode = "cl"
	CountryCodeCn CountryCode = "cn"
	CountryCodeCx CountryCode = "cx"
	CountryCodeCc CountryCode = "cc"
	CountryCodeCo CountryCode = "co"
	CountryCodeKm CountryCode = "km"
	CountryCodeCd CountryCode = "cd"
	CountryCodeCg CountryCode = "cg"
	CountryCodeCk CountryCode = "ck"
	CountryCodeCr CountryCode = "cr"
	CountryCodeHr CountryCode = "hr"
	CountryCodeCu CountryCode = "cu"
	CountryCodeCw CountryCode = "cw"
	CountryCodeCy CountryCode = "cy"
	CountryCodeCz CountryCode = "cz"
	CountryCodeCi CountryCode = "ci"
	CountryCodeDk CountryCode = "dk"
	CountryCodeDj CountryCode = "dj"
	CountryCodeDm CountryCode = "dm"
	CountryCodeDo CountryCode = "do"
	CountryCodeEc CountryCode = "ec"
	CountryCodeEg CountryCode = "eg"
	CountryCodeSv CountryCode = "sv"
	CountryCodeGq CountryCode = "gq"
	CountryCodeEr CountryCode = "er"
	CountryCodeEe CountryCode = "ee"
	CountryCodeSz CountryCode = "sz"
	CountryCodeEt CountryCode = "et"
	CountryCodeFk CountryCode = "fk"
	CountryCodeFo CountryCode = "fo"
	CountryCodeFj CountryCode = "fj"
	CountryCodeFi CountryCode = "fi"
	CountryCodeFr CountryCode = "fr"
	CountryCodeGf CountryCode = "gf"
	CountryCodePf CountryCode = "pf"
	CountryCodeTf CountryCode = "tf"
	CountryCodeGa CountryCode = "ga"
	CountryCodeGm CountryCode = "gm"
	CountryCodeGe CountryCode = "ge"
	CountryCodeDe CountryCode = "de"
	CountryCodeGh CountryCode = "gh"
	CountryCodeGi CountryCode = "gi"
	CountryCodeGr CountryCode = "gr"
	CountryCodeGl CountryCode = "gl"
	CountryCodeGd CountryCode = "gd"
	CountryCodeGp CountryCode = "gp"
	CountryCodeGu CountryCode = "gu"
	CountryCodeGt CountryCode = "gt"
	CountryCodeGg CountryCode = "gg"
	CountryCodeGn CountryCode = "gn"
	CountryCodeGw CountryCode = "gw"
	CountryCodeGy CountryCode = "gy"
	CountryCodeHt CountryCode = "ht"
	CountryCodeHm CountryCode = "hm"
	CountryCodeVa CountryCode = "va"
	CountryCodeHn CountryCode = "hn"
	CountryCodeHk CountryCode = "hk"
	CountryCodeHu CountryCode = "hu"
	CountryCodeIs CountryCode = "is"
	CountryCodeIn CountryCode = "in"
	CountryCodeID CountryCode = "id"
	CountryCodeIr CountryCode = "ir"
	CountryCodeIq CountryCode = "iq"
	CountryCodeIe CountryCode = "ie"
	CountryCodeIm CountryCode = "im"
	CountryCodeIl CountryCode = "il"
	CountryCodeIt CountryCode = "it"
	CountryCodeJm CountryCode = "jm"
	CountryCodeJp CountryCode = "jp"
	CountryCodeJe CountryCode = "je"
	CountryCodeJo CountryCode = "jo"
	CountryCodeKz CountryCode = "kz"
	CountryCodeKe CountryCode = "ke"
	CountryCodeKi CountryCode = "ki"
	CountryCodeKp CountryCode = "kp"
	CountryCodeKr CountryCode = "kr"
	CountryCodeKw CountryCode = "kw"
	CountryCodeKg CountryCode = "kg"
	CountryCodeLa CountryCode = "la"
	CountryCodeLv CountryCode = "lv"
	CountryCodeLb CountryCode = "lb"
	CountryCodeLs CountryCode = "ls"
	CountryCodeLr CountryCode = "lr"
	CountryCodeLy CountryCode = "ly"
	CountryCodeLi CountryCode = "li"
	CountryCodeLt CountryCode = "lt"
	CountryCodeLu CountryCode = "lu"
	CountryCodeMo CountryCode = "mo"
	CountryCodeMg CountryCode = "mg"
	CountryCodeMw CountryCode = "mw"
	CountryCodeMy CountryCode = "my"
	CountryCodeMv CountryCode = "mv"
	CountryCodeMl CountryCode = "ml"
	CountryCodeMt CountryCode = "mt"
	CountryCodeMh CountryCode = "mh"
	CountryCodeMq CountryCode = "mq"
	CountryCodeMr CountryCode = "mr"
	CountryCodeMu CountryCode = "mu"
	CountryCodeYt CountryCode = "yt"
	CountryCodeMx CountryCode = "mx"
	CountryCodeFm CountryCode = "fm"
	CountryCodeMd CountryCode = "md"
	CountryCodeMc CountryCode = "mc"
	CountryCodeMn CountryCode = "mn"
	CountryCodeMe CountryCode = "me"
	CountryCodeMs CountryCode = "ms"
	CountryCodeMa CountryCode = "ma"
	CountryCodeMz CountryCode = "mz"
	CountryCodeMm CountryCode = "mm"
	CountryCodeNa CountryCode = "na"
	CountryCodeNr CountryCode = "nr"
	CountryCodeNp CountryCode = "np"
	CountryCodeNl CountryCode = "nl"
	CountryCodeNc CountryCode = "nc"
	CountryCodeNz CountryCode = "nz"
	CountryCodeNi CountryCode = "ni"
	CountryCodeNe CountryCode = "ne"
	CountryCodeNg CountryCode = "ng"
	CountryCodeNu CountryCode = "nu"
	CountryCodeNf CountryCode = "nf"
	CountryCodeMp CountryCode = "mp"
	CountryCodeNo CountryCode = "no"
	CountryCodeOm CountryCode = "om"
	CountryCodePk CountryCode = "pk"
	CountryCodePw CountryCode = "pw"
	CountryCodePs CountryCode = "ps"
	CountryCodePa CountryCode = "pa"
	CountryCodePg CountryCode = "pg"
	CountryCodePy CountryCode = "py"
	CountryCodePe CountryCode = "pe"
	CountryCodePh CountryCode = "ph"
	CountryCodePn CountryCode = "pn"
	CountryCodePl CountryCode = "pl"
	CountryCodePt CountryCode = "pt"
	CountryCodePr CountryCode = "pr"
	CountryCodeQa CountryCode = "qa"
	CountryCodeMk CountryCode = "mk"
	CountryCodeRo CountryCode = "ro"
	CountryCodeRu CountryCode = "ru"
	CountryCodeRw CountryCode = "rw"
	CountryCodeRe CountryCode = "re"
	CountryCodeBl CountryCode = "bl"
	CountryCodeSh CountryCode = "sh"
	CountryCodeKn CountryCode = "kn"
	CountryCodeLc CountryCode = "lc"
	CountryCodeMf CountryCode = "mf"
	CountryCodePm CountryCode = "pm"
	CountryCodeVc CountryCode = "vc"
	CountryCodeWs CountryCode = "ws"
	CountryCodeSm CountryCode = "sm"
	CountryCodeSt CountryCode = "st"
	CountryCodeSa CountryCode = "sa"
	CountryCodeSn CountryCode = "sn"
	CountryCodeRs CountryCode = "rs"
	CountryCodeSc CountryCode = "sc"
	CountryCodeSl CountryCode = "sl"
	CountryCodeSg CountryCode = "sg"
	CountryCodeSx CountryCode = "sx"
	CountryCodeSk CountryCode = "sk"
	CountryCodeSi CountryCode = "si"
	CountryCodeSb CountryCode = "sb"
	CountryCodeSo CountryCode = "so"
	CountryCodeZa CountryCode = "za"
	CountryCodeGs CountryCode = "gs"
	CountryCodeSs CountryCode = "ss"
	CountryCodeEs CountryCode = "es"
	CountryCodeLk CountryCode = "lk"
	CountryCodeSd CountryCode = "sd"
	CountryCodeSr CountryCode = "sr"
	CountryCodeSj CountryCode = "sj"
	CountryCodeSe CountryCode = "se"
	CountryCodeCh CountryCode = "ch"
	CountryCodeSy CountryCode = "sy"
	CountryCodeTw CountryCode = "tw"
	CountryCodeTj CountryCode = "tj"
	CountryCodeTz CountryCode = "tz"
	CountryCodeTh CountryCode = "th"
	CountryCodeTl CountryCode = "tl"
	CountryCodeTg CountryCode = "tg"
	CountryCodeTk CountryCode = "tk"
	CountryCodeTo CountryCode = "to"
	CountryCodeTt CountryCode = "tt"
	CountryCodeTn CountryCode = "tn"
	CountryCodeTr CountryCode = "tr"
	CountryCodeTm CountryCode = "tm"
	CountryCodeTc CountryCode = "tc"
	CountryCodeTv CountryCode = "tv"
	CountryCodeUg CountryCode = "ug"
	CountryCodeUa CountryCode = "ua"
	CountryCodeAe CountryCode = "ae"
	CountryCodeGb CountryCode = "gb"
	CountryCodeUm CountryCode = "um"
	CountryCodeUs CountryCode = "us"
	CountryCodeUy CountryCode = "uy"
	CountryCodeUz CountryCode = "uz"
	CountryCodeVu CountryCode = "vu"
	CountryCodeVe CountryCode = "ve"
	CountryCodeVn CountryCode = "vn"
	CountryCodeVg CountryCode = "vg"
	CountryCodeVi CountryCode = "vi"
	CountryCodeWf CountryCode = "wf"
	CountryCodeEh CountryCode = "eh"
	CountryCodeYe CountryCode = "ye"
	CountryCodeZm CountryCode = "zm"
	CountryCodeZw CountryCode = "zw"
	CountryCodeAx CountryCode = "ax"
)

func (e CountryCode) ToPointer() *CountryCode {
	return &e
}

func (e *CountryCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "af":
		fallthrough
	case "al":
		fallthrough
	case "dz":
		fallthrough
	case "as":
		fallthrough
	case "ad":
		fallthrough
	case "ao":
		fallthrough
	case "ai":
		fallthrough
	case "aq":
		fallthrough
	case "ag":
		fallthrough
	case "ar":
		fallthrough
	case "am":
		fallthrough
	case "aw":
		fallthrough
	case "au":
		fallthrough
	case "at":
		fallthrough
	case "az":
		fallthrough
	case "bs":
		fallthrough
	case "bh":
		fallthrough
	case "bd":
		fallthrough
	case "bb":
		fallthrough
	case "by":
		fallthrough
	case "be":
		fallthrough
	case "bz":
		fallthrough
	case "bj":
		fallthrough
	case "bm":
		fallthrough
	case "bt":
		fallthrough
	case "bo":
		fallthrough
	case "bq":
		fallthrough
	case "ba":
		fallthrough
	case "bw":
		fallthrough
	case "bv":
		fallthrough
	case "br":
		fallthrough
	case "io":
		fallthrough
	case "bn":
		fallthrough
	case "bg":
		fallthrough
	case "bf":
		fallthrough
	case "bi":
		fallthrough
	case "cv":
		fallthrough
	case "kh":
		fallthrough
	case "cm":
		fallthrough
	case "ca":
		fallthrough
	case "ky":
		fallthrough
	case "cf":
		fallthrough
	case "td":
		fallthrough
	case "cl":
		fallthrough
	case "cn":
		fallthrough
	case "cx":
		fallthrough
	case "cc":
		fallthrough
	case "co":
		fallthrough
	case "km":
		fallthrough
	case "cd":
		fallthrough
	case "cg":
		fallthrough
	case "ck":
		fallthrough
	case "cr":
		fallthrough
	case "hr":
		fallthrough
	case "cu":
		fallthrough
	case "cw":
		fallthrough
	case "cy":
		fallthrough
	case "cz":
		fallthrough
	case "ci":
		fallthrough
	case "dk":
		fallthrough
	case "dj":
		fallthrough
	case "dm":
		fallthrough
	case "do":
		fallthrough
	case "ec":
		fallthrough
	case "eg":
		fallthrough
	case "sv":
		fallthrough
	case "gq":
		fallthrough
	case "er":
		fallthrough
	case "ee":
		fallthrough
	case "sz":
		fallthrough
	case "et":
		fallthrough
	case "fk":
		fallthrough
	case "fo":
		fallthrough
	case "fj":
		fallthrough
	case "fi":
		fallthrough
	case "fr":
		fallthrough
	case "gf":
		fallthrough
	case "pf":
		fallthrough
	case "tf":
		fallthrough
	case "ga":
		fallthrough
	case "gm":
		fallthrough
	case "ge":
		fallthrough
	case "de":
		fallthrough
	case "gh":
		fallthrough
	case "gi":
		fallthrough
	case "gr":
		fallthrough
	case "gl":
		fallthrough
	case "gd":
		fallthrough
	case "gp":
		fallthrough
	case "gu":
		fallthrough
	case "gt":
		fallthrough
	case "gg":
		fallthrough
	case "gn":
		fallthrough
	case "gw":
		fallthrough
	case "gy":
		fallthrough
	case "ht":
		fallthrough
	case "hm":
		fallthrough
	case "va":
		fallthrough
	case "hn":
		fallthrough
	case "hk":
		fallthrough
	case "hu":
		fallthrough
	case "is":
		fallthrough
	case "in":
		fallthrough
	case "id":
		fallthrough
	case "ir":
		fallthrough
	case "iq":
		fallthrough
	case "ie":
		fallthrough
	case "im":
		fallthrough
	case "il":
		fallthrough
	case "it":
		fallthrough
	case "jm":
		fallthrough
	case "jp":
		fallthrough
	case "je":
		fallthrough
	case "jo":
		fallthrough
	case "kz":
		fallthrough
	case "ke":
		fallthrough
	case "ki":
		fallthrough
	case "kp":
		fallthrough
	case "kr":
		fallthrough
	case "kw":
		fallthrough
	case "kg":
		fallthrough
	case "la":
		fallthrough
	case "lv":
		fallthrough
	case "lb":
		fallthrough
	case "ls":
		fallthrough
	case "lr":
		fallthrough
	case "ly":
		fallthrough
	case "li":
		fallthrough
	case "lt":
		fallthrough
	case "lu":
		fallthrough
	case "mo":
		fallthrough
	case "mg":
		fallthrough
	case "mw":
		fallthrough
	case "my":
		fallthrough
	case "mv":
		fallthrough
	case "ml":
		fallthrough
	case "mt":
		fallthrough
	case "mh":
		fallthrough
	case "mq":
		fallthrough
	case "mr":
		fallthrough
	case "mu":
		fallthrough
	case "yt":
		fallthrough
	case "mx":
		fallthrough
	case "fm":
		fallthrough
	case "md":
		fallthrough
	case "mc":
		fallthrough
	case "mn":
		fallthrough
	case "me":
		fallthrough
	case "ms":
		fallthrough
	case "ma":
		fallthrough
	case "mz":
		fallthrough
	case "mm":
		fallthrough
	case "na":
		fallthrough
	case "nr":
		fallthrough
	case "np":
		fallthrough
	case "nl":
		fallthrough
	case "nc":
		fallthrough
	case "nz":
		fallthrough
	case "ni":
		fallthrough
	case "ne":
		fallthrough
	case "ng":
		fallthrough
	case "nu":
		fallthrough
	case "nf":
		fallthrough
	case "mp":
		fallthrough
	case "no":
		fallthrough
	case "om":
		fallthrough
	case "pk":
		fallthrough
	case "pw":
		fallthrough
	case "ps":
		fallthrough
	case "pa":
		fallthrough
	case "pg":
		fallthrough
	case "py":
		fallthrough
	case "pe":
		fallthrough
	case "ph":
		fallthrough
	case "pn":
		fallthrough
	case "pl":
		fallthrough
	case "pt":
		fallthrough
	case "pr":
		fallthrough
	case "qa":
		fallthrough
	case "mk":
		fallthrough
	case "ro":
		fallthrough
	case "ru":
		fallthrough
	case "rw":
		fallthrough
	case "re":
		fallthrough
	case "bl":
		fallthrough
	case "sh":
		fallthrough
	case "kn":
		fallthrough
	case "lc":
		fallthrough
	case "mf":
		fallthrough
	case "pm":
		fallthrough
	case "vc":
		fallthrough
	case "ws":
		fallthrough
	case "sm":
		fallthrough
	case "st":
		fallthrough
	case "sa":
		fallthrough
	case "sn":
		fallthrough
	case "rs":
		fallthrough
	case "sc":
		fallthrough
	case "sl":
		fallthrough
	case "sg":
		fallthrough
	case "sx":
		fallthrough
	case "sk":
		fallthrough
	case "si":
		fallthrough
	case "sb":
		fallthrough
	case "so":
		fallthrough
	case "za":
		fallthrough
	case "gs":
		fallthrough
	case "ss":
		fallthrough
	case "es":
		fallthrough
	case "lk":
		fallthrough
	case "sd":
		fallthrough
	case "sr":
		fallthrough
	case "sj":
		fallthrough
	case "se":
		fallthrough
	case "ch":
		fallthrough
	case "sy":
		fallthrough
	case "tw":
		fallthrough
	case "tj":
		fallthrough
	case "tz":
		fallthrough
	case "th":
		fallthrough
	case "tl":
		fallthrough
	case "tg":
		fallthrough
	case "tk":
		fallthrough
	case "to":
		fallthrough
	case "tt":
		fallthrough
	case "tn":
		fallthrough
	case "tr":
		fallthrough
	case "tm":
		fallthrough
	case "tc":
		fallthrough
	case "tv":
		fallthrough
	case "ug":
		fallthrough
	case "ua":
		fallthrough
	case "ae":
		fallthrough
	case "gb":
		fallthrough
	case "um":
		fallthrough
	case "us":
		fallthrough
	case "uy":
		fallthrough
	case "uz":
		fallthrough
	case "vu":
		fallthrough
	case "ve":
		fallthrough
	case "vn":
		fallthrough
	case "vg":
		fallthrough
	case "vi":
		fallthrough
	case "wf":
		fallthrough
	case "eh":
		fallthrough
	case "ye":
		fallthrough
	case "zm":
		fallthrough
	case "zw":
		fallthrough
	case "ax":
		*e = CountryCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CountryCode: %v", v)
	}
}
