// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateRecipeDeployment - Represents a request to create a new recipe deployment
type CreateRecipeDeployment struct {
	DisplayName *string `json:"display_name"`
	Name        string  `json:"name"`
	// Represents container group networking parameters
	Networking *CreateRecipeNetworking `json:"networking,omitempty"`
	RecipeName string                  `json:"recipe_name"`
	Replicas   int64                   `json:"replicas"`
}

func (o *CreateRecipeDeployment) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *CreateRecipeDeployment) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateRecipeDeployment) GetNetworking() *CreateRecipeNetworking {
	if o == nil {
		return nil
	}
	return o.Networking
}

func (o *CreateRecipeDeployment) GetRecipeName() string {
	if o == nil {
		return ""
	}
	return o.RecipeName
}

func (o *CreateRecipeDeployment) GetReplicas() int64 {
	if o == nil {
		return 0
	}
	return o.Replicas
}
