// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateContainerGroupNetworking - Represents container group networking parameters
type CreateContainerGroupNetworking struct {
	Auth     bool                        `json:"auth"`
	Port     int64                       `json:"port"`
	Protocol ContainerNetworkingProtocol `json:"protocol"`
}

func (o *CreateContainerGroupNetworking) GetAuth() bool {
	if o == nil {
		return false
	}
	return o.Auth
}

func (o *CreateContainerGroupNetworking) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *CreateContainerGroupNetworking) GetProtocol() ContainerNetworkingProtocol {
	if o == nil {
		return ContainerNetworkingProtocol("")
	}
	return o.Protocol
}
