// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateRecipeNetworking - Represents container group networking parameters
type CreateRecipeNetworking struct {
	Auth     bool                     `json:"auth"`
	Port     int64                    `json:"port"`
	Protocol RecipeNetworkingProtocol `json:"protocol"`
}

func (o *CreateRecipeNetworking) GetAuth() bool {
	if o == nil {
		return false
	}
	return o.Auth
}

func (o *CreateRecipeNetworking) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *CreateRecipeNetworking) GetProtocol() RecipeNetworkingProtocol {
	if o == nil {
		return RecipeNetworkingProtocol("")
	}
	return o.Protocol
}
