// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GpuClass - Represents a GPU Class
type GpuClass struct {
	// The GPU class name
	Name string `json:"name"`
}

func (o *GpuClass) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
