// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GpuClassesList - Represents a list of GPU classes
type GpuClassesList struct {
	// The list of GPU classes
	Items []GpuClass `json:"items"`
}

func (o *GpuClassesList) GetItems() []GpuClass {
	if o == nil {
		return []GpuClass{}
	}
	return o.Items
}
