// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/utils"
)

// ProblemDetails - Represents a problem
type ProblemDetails struct {
	// A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`
	// The URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`
	// The HTTP status code generated by the origin server
	Status *int64 `json:"status,omitempty"`
	// A short, human-readable summary of the problem type
	Title *string `json:"title,omitempty"`
	// The URI reference that identifies the problem type
	Type *string `default:"about:blank" json:"type"`
}

func (p ProblemDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProblemDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProblemDetails) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *ProblemDetails) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *ProblemDetails) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ProblemDetails) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *ProblemDetails) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
