// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/utils"
	"time"
)

// Quotas - Represents the organization quotas
type Quotas struct {
	ContainerGroupsQuotas ContainerGroupsQuotas `json:"container_groups_quotas"`
	// The time the resource was created
	CreateTime    *time.Time    `json:"create_time,omitempty"`
	RecipesQuotas RecipesQuotas `json:"recipes_quotas"`
	// The time the resource was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

func (q Quotas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *Quotas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Quotas) GetContainerGroupsQuotas() ContainerGroupsQuotas {
	if o == nil {
		return ContainerGroupsQuotas{}
	}
	return o.ContainerGroupsQuotas
}

func (o *Quotas) GetCreateTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreateTime
}

func (o *Quotas) GetRecipesQuotas() RecipesQuotas {
	if o == nil {
		return RecipesQuotas{}
	}
	return o.RecipesQuotas
}

func (o *Quotas) GetUpdateTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdateTime
}
