// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Recipe - Represents a recipe
type Recipe struct {
	// The unique identifier
	ID string `json:"id"`
	// The recipe name
	Name string `json:"name"`
	// Represents recipe networking parameters
	Networking *RecipeNetworking `json:"networking,omitempty"`
	// A markdown file containing a brief summary of the recipe
	Readme string `json:"readme"`
	// Represents a recipe resources
	Resources *RecipeResources `json:"resources,omitempty"`
}

func (o *Recipe) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Recipe) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Recipe) GetNetworking() *RecipeNetworking {
	if o == nil {
		return nil
	}
	return o.Networking
}

func (o *Recipe) GetReadme() string {
	if o == nil {
		return ""
	}
	return o.Readme
}

func (o *Recipe) GetResources() *RecipeResources {
	if o == nil {
		return nil
	}
	return o.Resources
}
