// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RecipesQuotas struct {
	MaxCreatedRecipeDeployments int64 `json:"max_created_recipe_deployments"`
	RecipeInstanceQuota         int64 `json:"recipe_instance_quota"`
}

func (o *RecipesQuotas) GetMaxCreatedRecipeDeployments() int64 {
	if o == nil {
		return 0
	}
	return o.MaxCreatedRecipeDeployments
}

func (o *RecipesQuotas) GetRecipeInstanceQuota() int64 {
	if o == nil {
		return 0
	}
	return o.RecipeInstanceQuota
}
