// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RecipeList - Represents a list of recipes
type RecipeList struct {
	// The list of items
	Items []Recipe `json:"items"`
}

func (o *RecipeList) GetItems() []Recipe {
	if o == nil {
		return []Recipe{}
	}
	return o.Items
}
