// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RecipeNetworking - Represents recipe networking parameters
type RecipeNetworking struct {
	Auth     bool                     `json:"auth"`
	DNS      string                   `json:"dns"`
	Port     int64                    `json:"port"`
	Protocol RecipeNetworkingProtocol `json:"protocol"`
}

func (o *RecipeNetworking) GetAuth() bool {
	if o == nil {
		return false
	}
	return o.Auth
}

func (o *RecipeNetworking) GetDNS() string {
	if o == nil {
		return ""
	}
	return o.DNS
}

func (o *RecipeNetworking) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *RecipeNetworking) GetProtocol() RecipeNetworkingProtocol {
	if o == nil {
		return RecipeNetworkingProtocol("")
	}
	return o.Protocol
}
