// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RecipeDeployment - Represents a deployed recipe
type RecipeDeployment struct {
	// Represents a container group state
	CurrentState ContainerGroupState `json:"current_state"`
	DisplayName  string              `json:"display_name"`
	ID           string              `json:"id"`
	Name         string              `json:"name"`
	// Represents recipe networking parameters
	Networking *RecipeNetworking `json:"networking,omitempty"`
	// Represents a recipe
	Recipe   Recipe `json:"recipe"`
	Replicas int64  `json:"replicas"`
}

func (o *RecipeDeployment) GetCurrentState() ContainerGroupState {
	if o == nil {
		return ContainerGroupState{}
	}
	return o.CurrentState
}

func (o *RecipeDeployment) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *RecipeDeployment) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RecipeDeployment) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RecipeDeployment) GetNetworking() *RecipeNetworking {
	if o == nil {
		return nil
	}
	return o.Networking
}

func (o *RecipeDeployment) GetRecipe() Recipe {
	if o == nil {
		return Recipe{}
	}
	return o.Recipe
}

func (o *RecipeDeployment) GetReplicas() int64 {
	if o == nil {
		return 0
	}
	return o.Replicas
}
