// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RecipeNetworkingProtocol string

const (
	RecipeNetworkingProtocolHTTP RecipeNetworkingProtocol = "http"
)

func (e RecipeNetworkingProtocol) ToPointer() *RecipeNetworkingProtocol {
	return &e
}

func (e *RecipeNetworkingProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		*e = RecipeNetworkingProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipeNetworkingProtocol: %v", v)
	}
}
