// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RecipeResources - Represents a recipe resources
type RecipeResources struct {
	CPU      int64  `json:"cpu"`
	GpuClass string `json:"gpu_class"`
	RAM      int64  `json:"ram"`
}

func (o *RecipeResources) GetCPU() int64 {
	if o == nil {
		return 0
	}
	return o.CPU
}

func (o *RecipeResources) GetGpuClass() string {
	if o == nil {
		return ""
	}
	return o.GpuClass
}

func (o *RecipeResources) GetRAM() int64 {
	if o == nil {
		return 0
	}
	return o.RAM
}
