// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	APIKeyAuth string `security:"scheme,type=apiKey,subtype=header,name=Salad-Api-Key"`
}

func (o *Security) GetAPIKeyAuth() string {
	if o == nil {
		return ""
	}
	return o.APIKeyAuth
}
