// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateContainerGroup - Represents a request to update a container group
type UpdateContainerGroup struct {
	DisplayName *string `json:"display_name,omitempty"`
	Replicas    *int64  `json:"replicas,omitempty"`
}

func (o *UpdateContainerGroup) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *UpdateContainerGroup) GetReplicas() *int64 {
	if o == nil {
		return nil
	}
	return o.Replicas
}
