// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRecipeDeployment - Represents a request to update a recipe deployment
type UpdateRecipeDeployment struct {
	DisplayName *string `json:"display_name,omitempty"`
	Replicas    *int64  `json:"replicas,omitempty"`
}

func (o *UpdateRecipeDeployment) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *UpdateRecipeDeployment) GetReplicas() *int64 {
	if o == nil {
		return nil
	}
	return o.Replicas
}
