// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"time"
)

func (r *ContainerGroupInstancesDataSourceModel) RefreshFromGetResponse(resp *shared.ContainerGroupInstances) {
	r.Instances = nil
	for _, instancesItem := range resp.Instances {
		var instances1 Instances
		instances1.MachineID = types.StringValue(instancesItem.MachineID)
		instances1.State = types.StringValue(string(instancesItem.State))
		instances1.UpdateTime = types.StringValue(instancesItem.UpdateTime.Format(time.RFC3339Nano))
		r.Instances = append(r.Instances, instances1)
	}
}
