// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/operations"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/squat/terraform-provider-saladcloud/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &ContainerGroupDataSource{}
var _ datasource.DataSourceWithConfigure = &ContainerGroupDataSource{}

func NewContainerGroupDataSource() datasource.DataSource {
	return &ContainerGroupDataSource{}
}

// ContainerGroupDataSource is the data source implementation.
type ContainerGroupDataSource struct {
	client *sdk.SDK
}

// ContainerGroupDataSourceModel describes the data model.
type ContainerGroupDataSourceModel struct {
	Container        Container1                `tfsdk:"container"`
	CountryCodes     []types.String            `tfsdk:"country_codes"`
	CreateTime       types.String              `tfsdk:"create_time"`
	CurrentState     ContainerGroupState       `tfsdk:"current_state"`
	DisplayName      types.String              `tfsdk:"display_name"`
	ID               types.String              `tfsdk:"id"`
	LivenessProbe    *ContainerGroupProbe      `tfsdk:"liveness_probe"`
	Name             types.String              `tfsdk:"name"`
	Networking       *ContainerGroupNetworking `tfsdk:"networking"`
	OrganizationName types.String              `tfsdk:"organization_name"`
	ProjectName      types.String              `tfsdk:"project_name"`
	ReadinessProbe   *ContainerGroupProbe      `tfsdk:"readiness_probe"`
	Replicas         types.Int64               `tfsdk:"replicas"`
	RestartPolicy    types.String              `tfsdk:"restart_policy"`
	StartupProbe     *ContainerGroupProbe      `tfsdk:"startup_probe"`
	UpdateTime       types.String              `tfsdk:"update_time"`
}

// Metadata returns the data source type name.
func (r *ContainerGroupDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_container_group"
}

// Schema defines the schema for the data source.
func (r *ContainerGroupDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "ContainerGroup DataSource",

		Attributes: map[string]schema.Attribute{
			"container": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"command": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"environment_variables": schema.MapAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"image": schema.StringAttribute{
						Computed: true,
					},
					"logging": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"new_relic": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"host": schema.StringAttribute{
										Computed: true,
									},
									"ingestion_key": schema.StringAttribute{
										Computed: true,
									},
								},
							},
							"splunk": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"host": schema.StringAttribute{
										Computed: true,
									},
									"token": schema.StringAttribute{
										Computed: true,
									},
								},
							},
							"tcp": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"host": schema.StringAttribute{
										Computed: true,
									},
									"port": schema.Int64Attribute{
										Computed: true,
									},
								},
							},
						},
					},
					"resources": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"cpu": schema.Int64Attribute{
								Computed: true,
							},
							"gpu_class": schema.StringAttribute{
								Computed: true,
							},
							"memory": schema.Int64Attribute{
								Computed: true,
							},
						},
						Description: `Represents a container resource requirements`,
					},
				},
				Description: `Represents a container`,
			},
			"country_codes": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"create_time": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
			"current_state": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"description": schema.StringAttribute{
						Computed: true,
					},
					"finish_time": schema.StringAttribute{
						Computed: true,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"instance_status_count": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"allocating_count": schema.Int64Attribute{
								Computed: true,
							},
							"creating_count": schema.Int64Attribute{
								Computed: true,
							},
							"running_count": schema.Int64Attribute{
								Computed: true,
							},
						},
						Description: `Represents a container group instance status count`,
					},
					"start_time": schema.StringAttribute{
						Computed: true,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"status": schema.StringAttribute{
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"pending",
								"running",
								"stopped",
								"succeeded",
								"failed",
								"deploying",
							),
						},
						Description: `must be one of ["pending", "running", "stopped", "succeeded", "failed", "deploying"]`,
					},
				},
				Description: `Represents a container group state`,
			},
			"display_name": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"liveness_probe": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"exec": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"command": schema.ListAttribute{
								Computed:    true,
								ElementType: types.StringType,
							},
						},
					},
					"failure_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"grpc": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"service": schema.StringAttribute{
								Computed: true,
							},
						},
					},
					"http": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"headers": schema.ListNestedAttribute{
								Computed: true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Computed: true,
										},
										"value": schema.StringAttribute{
											Computed: true,
										},
									},
								},
							},
							"path": schema.StringAttribute{
								Computed: true,
							},
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"scheme": schema.StringAttribute{
								Computed: true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"http",
									),
								},
								Description: `must be one of ["http"]`,
							},
						},
					},
					"initial_delay_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"period_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"success_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"tcp": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
						},
					},
					"timeout_seconds": schema.Int64Attribute{
						Computed: true,
					},
				},
				Description: `Represents container group probe`,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `The unique container group name`,
			},
			"networking": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"auth": schema.BoolAttribute{
						Computed: true,
					},
					"dns": schema.StringAttribute{
						Computed: true,
					},
					"port": schema.Int64Attribute{
						Computed: true,
					},
					"protocol": schema.StringAttribute{
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"http",
							),
						},
						Description: `must be one of ["http"]`,
					},
				},
				Description: `Represents container group networking parameters`,
			},
			"organization_name": schema.StringAttribute{
				Required:    true,
				Description: `The unique organization name`,
			},
			"project_name": schema.StringAttribute{
				Required:    true,
				Description: `The unique project name`,
			},
			"readiness_probe": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"exec": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"command": schema.ListAttribute{
								Computed:    true,
								ElementType: types.StringType,
							},
						},
					},
					"failure_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"grpc": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"service": schema.StringAttribute{
								Computed: true,
							},
						},
					},
					"http": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"headers": schema.ListNestedAttribute{
								Computed: true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Computed: true,
										},
										"value": schema.StringAttribute{
											Computed: true,
										},
									},
								},
							},
							"path": schema.StringAttribute{
								Computed: true,
							},
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"scheme": schema.StringAttribute{
								Computed: true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"http",
									),
								},
								Description: `must be one of ["http"]`,
							},
						},
					},
					"initial_delay_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"period_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"success_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"tcp": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
						},
					},
					"timeout_seconds": schema.Int64Attribute{
						Computed: true,
					},
				},
				Description: `Represents container group probe`,
			},
			"replicas": schema.Int64Attribute{
				Computed: true,
			},
			"restart_policy": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"always",
						"on_failure",
						"never",
					),
				},
				Description: `must be one of ["always", "on_failure", "never"]`,
			},
			"startup_probe": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"exec": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"command": schema.ListAttribute{
								Computed:    true,
								ElementType: types.StringType,
							},
						},
					},
					"failure_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"grpc": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"service": schema.StringAttribute{
								Computed: true,
							},
						},
					},
					"http": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"headers": schema.ListNestedAttribute{
								Computed: true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Computed: true,
										},
										"value": schema.StringAttribute{
											Computed: true,
										},
									},
								},
							},
							"path": schema.StringAttribute{
								Computed: true,
							},
							"port": schema.Int64Attribute{
								Computed: true,
							},
							"scheme": schema.StringAttribute{
								Computed: true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"http",
									),
								},
								Description: `must be one of ["http"]`,
							},
						},
					},
					"initial_delay_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"period_seconds": schema.Int64Attribute{
						Computed: true,
					},
					"success_threshold": schema.Int64Attribute{
						Computed: true,
					},
					"tcp": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								Computed: true,
							},
						},
					},
					"timeout_seconds": schema.Int64Attribute{
						Computed: true,
					},
				},
				Description: `Represents container group probe`,
			},
			"update_time": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
		},
	}
}

func (r *ContainerGroupDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *ContainerGroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *ContainerGroupDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	containerGroupName := data.Name.ValueString()
	organizationName := data.OrganizationName.ValueString()
	projectName := data.ProjectName.ValueString()
	request := operations.GetContainerGroupRequest{
		ContainerGroupName: containerGroupName,
		OrganizationName:   organizationName,
		ProjectName:        projectName,
	}
	res, err := r.client.ContainerGroups.GetContainerGroup(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.ContainerGroup == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.ContainerGroup)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
