// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
)

func (r *GPUClassesDataSourceModel) RefreshFromGetResponse(resp *shared.GpuClassesList) {
	if len(r.Items) > len(resp.Items) {
		r.Items = r.Items[:len(resp.Items)]
	}
	for itemsCount, itemsItem := range resp.Items {
		var items1 GpuClass
		items1.Name = types.StringValue(itemsItem.Name)
		if itemsCount+1 > len(r.Items) {
			r.Items = append(r.Items, items1)
		} else {
			r.Items[itemsCount].Name = items1.Name
		}
	}
}
