// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
)

func (r *GPUClassesDataSourceModel) RefreshFromGetResponse(resp *shared.GpuClassesList) {
	r.Items = nil
	for _, itemsItem := range resp.Items {
		var items1 GpuClass
		items1.Name = types.StringValue(itemsItem.Name)
		r.Items = append(r.Items, items1)
	}
}
