// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
)

func (r *RecipeDataSourceModel) RefreshFromGetResponse(resp *shared.Recipe) {
	r.ID = types.StringValue(resp.ID)
	r.Name = types.StringValue(resp.Name)
	if resp.Networking == nil {
		r.Networking = nil
	} else {
		r.Networking = &ContainerGroupNetworking{}
		r.Networking.Auth = types.BoolValue(resp.Networking.Auth)
		r.Networking.DNS = types.StringValue(resp.Networking.DNS)
		r.Networking.Port = types.Int64Value(resp.Networking.Port)
		r.Networking.Protocol = types.StringValue(string(resp.Networking.Protocol))
	}
	r.Readme = types.StringValue(resp.Readme)
	if resp.Resources == nil {
		r.Resources = nil
	} else {
		r.Resources = &RecipeResources{}
		r.Resources.CPU = types.Int64Value(resp.Resources.CPU)
		r.Resources.GpuClass = types.StringValue(resp.Resources.GpuClass)
		r.Resources.RAM = types.Int64Value(resp.Resources.RAM)
	}
}
