// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
)

func (r *RecipesDataSourceModel) RefreshFromGetResponse(resp *shared.RecipeList) {
	if len(r.Items) > len(resp.Items) {
		r.Items = r.Items[:len(resp.Items)]
	}
	for itemsCount, itemsItem := range resp.Items {
		var items1 Recipe
		items1.ID = types.StringValue(itemsItem.ID)
		items1.Name = types.StringValue(itemsItem.Name)
		if itemsItem.Networking == nil {
			items1.Networking = nil
		} else {
			items1.Networking = &ContainerGroupNetworking{}
			items1.Networking.Auth = types.BoolValue(itemsItem.Networking.Auth)
			items1.Networking.DNS = types.StringValue(itemsItem.Networking.DNS)
			items1.Networking.Port = types.Int64Value(itemsItem.Networking.Port)
			items1.Networking.Protocol = types.StringValue(string(itemsItem.Networking.Protocol))
		}
		items1.Readme = types.StringValue(itemsItem.Readme)
		if itemsItem.Resources == nil {
			items1.Resources = nil
		} else {
			items1.Resources = &RecipeResources{}
			items1.Resources.CPU = types.Int64Value(itemsItem.Resources.CPU)
			items1.Resources.GpuClass = types.StringValue(itemsItem.Resources.GpuClass)
			items1.Resources.RAM = types.Int64Value(itemsItem.Resources.RAM)
		}
		if itemsCount+1 > len(r.Items) {
			r.Items = append(r.Items, items1)
		} else {
			r.Items[itemsCount].ID = items1.ID
			r.Items[itemsCount].Name = items1.Name
			r.Items[itemsCount].Networking = items1.Networking
			r.Items[itemsCount].Readme = items1.Readme
			r.Items[itemsCount].Resources = items1.Resources
		}
	}
}
