// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RecipesQuotas struct {
	MaxCreatedRecipeDeployments types.Int64 `tfsdk:"max_created_recipe_deployments"`
	RecipeInstanceQuota         types.Int64 `tfsdk:"recipe_instance_quota"`
}
