// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ContainerGroupProbeGrpc struct {
	Port    types.Int64  `tfsdk:"port"`
	Service types.String `tfsdk:"service"`
}
