// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Logging struct {
	NewRelic *NewRelic `tfsdk:"new_relic"`
	Splunk   *Splunk   `tfsdk:"splunk"`
	TCP      *TCP      `tfsdk:"tcp"`
}
