// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ContainerGroupState struct {
	Description         types.String                      `tfsdk:"description"`
	FinishTime          types.String                      `tfsdk:"finish_time"`
	InstanceStatusCount ContainerGroupInstanceStatusCount `tfsdk:"instance_status_count"`
	StartTime           types.String                      `tfsdk:"start_time"`
	Status              types.String                      `tfsdk:"status"`
}
