// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Recipe struct {
	ID         types.String              `tfsdk:"id"`
	Name       types.String              `tfsdk:"name"`
	Networking *ContainerGroupNetworking `tfsdk:"networking"`
	Readme     types.String              `tfsdk:"readme"`
	Resources  *RecipeResources          `tfsdk:"resources"`
}
