// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ContainerGroupProbeHTTP struct {
	Headers []HTTPHeaders `tfsdk:"headers"`
	Path    types.String  `tfsdk:"path"`
	Port    types.Int64   `tfsdk:"port"`
	Scheme  types.String  `tfsdk:"scheme"`
}
