// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RecipeDeployment struct {
	CurrentState ContainerGroupState       `tfsdk:"current_state"`
	DisplayName  types.String              `tfsdk:"display_name"`
	ID           types.String              `tfsdk:"id"`
	Name         types.String              `tfsdk:"name"`
	Networking   *ContainerGroupNetworking `tfsdk:"networking"`
	Recipe       Recipe                    `tfsdk:"recipe"`
	Replicas     types.Int64               `tfsdk:"replicas"`
}
