// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type NewRelic struct {
	Host         types.String `tfsdk:"host"`
	IngestionKey types.String `tfsdk:"ingestion_key"`
}
