// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type RegistryAuthentication struct {
	AwsEcr    *AwsEcr    `tfsdk:"aws_ecr"`
	Basic     *Basic     `tfsdk:"basic"`
	DockerHub *DockerHub `tfsdk:"docker_hub"`
	GcpGcr    *GcpGcr    `tfsdk:"gcp_gcr"`
}
