// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type DockerHub struct {
	PersonalAccessToken types.String `tfsdk:"personal_access_token"`
	Username            types.String `tfsdk:"username"`
}
