// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ContainerGroupProbe struct {
	Exec                *ContainerGroupProbeExec `tfsdk:"exec"`
	FailureThreshold    types.Int64              `tfsdk:"failure_threshold"`
	Grpc                *ContainerGroupProbeGrpc `tfsdk:"grpc"`
	HTTP                *ContainerGroupProbeHTTP `tfsdk:"http"`
	InitialDelaySeconds types.Int64              `tfsdk:"initial_delay_seconds"`
	PeriodSeconds       types.Int64              `tfsdk:"period_seconds"`
	SuccessThreshold    types.Int64              `tfsdk:"success_threshold"`
	TCP                 *ContainerGroupProbeTCP  `tfsdk:"tcp"`
	TimeoutSeconds      types.Int64              `tfsdk:"timeout_seconds"`
}
