// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type HTTPHeaders struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}
