// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Instances struct {
	MachineID  types.String `tfsdk:"machine_id"`
	State      types.String `tfsdk:"state"`
	UpdateTime types.String `tfsdk:"update_time"`
}
