// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Container1 struct {
	Command              []types.String                `tfsdk:"command"`
	EnvironmentVariables map[string]types.String       `tfsdk:"environment_variables"`
	Image                types.String                  `tfsdk:"image"`
	Logging              *Logging                      `tfsdk:"logging"`
	Resources            ContainerResourceRequirements `tfsdk:"resources"`
}
