// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ContainerGroupsQuotas struct {
	ContainerInstanceQuota                  types.Int64 `tfsdk:"container_instance_quota"`
	MaxContainerGroupReallocationsPerMinute types.Int64 `tfsdk:"max_container_group_reallocations_per_minute"`
	MaxContainerGroupRecreatesPerMinute     types.Int64 `tfsdk:"max_container_group_recreates_per_minute"`
	MaxContainerGroupRestartsPerMinute      types.Int64 `tfsdk:"max_container_group_restarts_per_minute"`
	MaxCreatedContainerGroups               types.Int64 `tfsdk:"max_created_container_groups"`
}
