// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

//go:build tools

package tools

import (
	_ "github.com/brancz/gojsontoyaml"
	_ "github.com/mikefarah/yq/v4"
	_ "honnef.co/go/tools/cmd/staticcheck"
	// Documentation generation
	_ "github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs"
)
