// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateContainerGroupRequest struct {
	CreateContainerGroup shared.CreateContainerGroup `request:"mediaType=application/json"`
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
	// The unique project name
	ProjectName string `pathParam:"style=simple,explode=false,name=project_name"`
}

func (o *CreateContainerGroupRequest) GetCreateContainerGroup() shared.CreateContainerGroup {
	if o == nil {
		return shared.CreateContainerGroup{}
	}
	return o.CreateContainerGroup
}

func (o *CreateContainerGroupRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

func (o *CreateContainerGroupRequest) GetProjectName() string {
	if o == nil {
		return ""
	}
	return o.ProjectName
}

type CreateContainerGroupResponse struct {
	// Created
	ContainerGroup *shared.ContainerGroup
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// Bad Request
	ProblemDetails *shared.ProblemDetails
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateContainerGroupResponse) GetContainerGroup() *shared.ContainerGroup {
	if o == nil {
		return nil
	}
	return o.ContainerGroup
}

func (o *CreateContainerGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateContainerGroupResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateContainerGroupResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *CreateContainerGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateContainerGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
