// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetQuotasRequest struct {
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
}

func (o *GetQuotasRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

type GetQuotasResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Not Found
	ProblemDetails *shared.ProblemDetails
	// OK
	Quotas *shared.Quotas
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetQuotasResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetQuotasResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *GetQuotasResponse) GetQuotas() *shared.Quotas {
	if o == nil {
		return nil
	}
	return o.Quotas
}

func (o *GetQuotasResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetQuotasResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
