// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetRecipeRequest struct {
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
	// The unique recipe name
	RecipeName string `pathParam:"style=simple,explode=false,name=recipe_name"`
}

func (o *GetRecipeRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

func (o *GetRecipeRequest) GetRecipeName() string {
	if o == nil {
		return ""
	}
	return o.RecipeName
}

type GetRecipeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Not Found
	ProblemDetails *shared.ProblemDetails
	// OK
	Recipe *shared.Recipe
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRecipeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRecipeResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *GetRecipeResponse) GetRecipe() *shared.Recipe {
	if o == nil {
		return nil
	}
	return o.Recipe
}

func (o *GetRecipeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRecipeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
