// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListRecipesRequest struct {
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
}

func (o *ListRecipesRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

type ListRecipesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Not Found
	ProblemDetails *shared.ProblemDetails
	// OK
	RecipeList *shared.RecipeList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListRecipesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListRecipesResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *ListRecipesResponse) GetRecipeList() *shared.RecipeList {
	if o == nil {
		return nil
	}
	return o.RecipeList
}

func (o *ListRecipesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListRecipesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
