// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListGpuClassesRequest struct {
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
}

func (o *ListGpuClassesRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

type ListGpuClassesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GpuClassesList *shared.GpuClassesList
	// Not Found
	ProblemDetails *shared.ProblemDetails
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListGpuClassesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListGpuClassesResponse) GetGpuClassesList() *shared.GpuClassesList {
	if o == nil {
		return nil
	}
	return o.GpuClassesList
}

func (o *ListGpuClassesResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *ListGpuClassesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListGpuClassesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
