// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type RestartDeployedRecipeRequest struct {
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
	// The unique project name
	ProjectName string `pathParam:"style=simple,explode=false,name=project_name"`
	// The unique recipe deployment name
	RecipeDeploymentName string `pathParam:"style=simple,explode=false,name=recipe_deployment_name"`
}

func (o *RestartDeployedRecipeRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

func (o *RestartDeployedRecipeRequest) GetProjectName() string {
	if o == nil {
		return ""
	}
	return o.ProjectName
}

func (o *RestartDeployedRecipeRequest) GetRecipeDeploymentName() string {
	if o == nil {
		return ""
	}
	return o.RecipeDeploymentName
}

type RestartDeployedRecipeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Bad Request
	ProblemDetails *shared.ProblemDetails
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RestartDeployedRecipeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RestartDeployedRecipeResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *RestartDeployedRecipeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RestartDeployedRecipeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
