// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-saladcloud/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateContainerGroupRequest struct {
	UpdateContainerGroup shared.UpdateContainerGroup `request:"mediaType=application/json"`
	// The unique container group name
	ContainerGroupName string `pathParam:"style=simple,explode=false,name=container_group_name"`
	// The unique organization name
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
	// The unique project name
	ProjectName string `pathParam:"style=simple,explode=false,name=project_name"`
}

func (o *UpdateContainerGroupRequest) GetUpdateContainerGroup() shared.UpdateContainerGroup {
	if o == nil {
		return shared.UpdateContainerGroup{}
	}
	return o.UpdateContainerGroup
}

func (o *UpdateContainerGroupRequest) GetContainerGroupName() string {
	if o == nil {
		return ""
	}
	return o.ContainerGroupName
}

func (o *UpdateContainerGroupRequest) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

func (o *UpdateContainerGroupRequest) GetProjectName() string {
	if o == nil {
		return ""
	}
	return o.ProjectName
}

type UpdateContainerGroupResponse struct {
	// OK
	ContainerGroup *shared.ContainerGroup
	// HTTP response content type for this operation
	ContentType string
	// Bad Request
	ProblemDetails *shared.ProblemDetails
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateContainerGroupResponse) GetContainerGroup() *shared.ContainerGroup {
	if o == nil {
		return nil
	}
	return o.ContainerGroup
}

func (o *UpdateContainerGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateContainerGroupResponse) GetProblemDetails() *shared.ProblemDetails {
	if o == nil {
		return nil
	}
	return o.ProblemDetails
}

func (o *UpdateContainerGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateContainerGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
